export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/',
  CLUB: '/club',
  TEAMS: '/equipes',
  PLAYERS: '/joueurs',
  ATTENDANCE: '/presences',
  TEAM_ROLL_CALL: '/equipes/:id/appel',
  INVENTORY: '/inventaire',
  MESSAGES: '/messages',
  TEAM_DETAILS: '/equipes/:id',
  PLAYER_DETAILS: '/joueurs/:id',
};
